# Generated by Django 4.2 on 2023-05-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmenthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='patient.patient'),
        ),
        migrations.CreateModel(
            name='AllowedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.IntegerField()),
                ('allowing_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_appointments', to='patient.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_app', to='patient.patient')),
            ],
        ),
    ]
