# Generated by Django 4.2 on 2023-05-07 06:39

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=patient.models.upload_To),
        ),
    ]
