# Generated by Django 4.2 on 2023-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_appointment_meeting_link_alter_patient_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='new', max_length=15),
        ),
    ]
