# Generated by Django 4.2 on 2023-05-11 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('isBooked', models.BooleanField(default=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='doctor.dates')),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('S', 'Surgery'), ('C', 'Cardiology'), ('DT', 'Dermatalogy'), ('ENT', 'ENT'), ('G', 'Gynaecology'), ('N', 'Neurology'), ('OP', 'Orthopedic'), ('PT', 'Pediatric'), ('PY', 'Physiotherapy')], default='C', max_length=3)),
                ('feesperSession', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=doctor.models.upload_To)),
                ('pincode', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['specialization'],
            },
        ),
        migrations.AddField(
            model_name='dates',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('time', 'date'), name='date_time_unique'),
        ),
        migrations.AddConstraint(
            model_name='dates',
            constraint=models.UniqueConstraint(fields=('doctor_id', 'date'), name='date_dr_unique'),
        ),
    ]
