# Generated by Django 4.2 on 2023-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Rheumatologist', 'Rheumatologist'), ('ENT_specialist', 'ENT_specialist'), ('Cardiologist', 'Cardiologist'), ('Orthopedist', 'Orthopedist'), ('Neurologist', 'Neurologist'), ('Allergist_Immunologist', 'Allergist_Immunologist'), ('Urologist', 'Urologist'), ('Dermatologist', 'Dermatologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Ophthalmologist', 'Ophthalmologist'), ('General Physician', 'General Physician'), ('obstetrics and gynaecologist', 'obstetrics and gynaecologist'), ('paediatrician', 'paediatrician'), ('psychiatrist', 'psychiatrist'), ('Surgeon', 'Surgeon')], default='General Physician', max_length=50),
        ),
    ]
