# Generated by Django 4.2 on 2023-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('S', 'Surgery'), ('C', 'Cardiology'), ('DT', 'Dermatalogy'), ('ENT', 'ENT'), ('G', 'Gynaecology'), ('N', 'Neurology'), ('OP', 'Orthopedic'), ('PT', 'Pediatric'), ('PY', 'Physiotherapy')], default='C', max_length=3),
        ),
    ]
