# Generated by Django 4.2 on 2023-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_clinic_name_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='registration_num',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
