# Generated by Django 4.2 on 2023-05-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_slots',
        ),
    ]
