# Generated by Django 4.2 on 2023-05-08 13:32

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctor_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.models.upload_To),
        ),
    ]
