# Generated by Django 4.2 on 2023-05-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='doctor_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
            preserve_default=False,
        ),
    ]
