# Generated by Django 4.2 on 2023-05-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_dates_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
